#HUNTERS
Hunter.create(name: "Dean Winchester", age: 35, email: "deanwinchester@gmail.com", username: "SexyImpala79", password: "iloveapplepie")
Hunter.create(name: "Sam Winchester", age: 28, email: "samwinchester@gmail.com", username: "LucyIsGone42", password: "shouldhavebeenalawyerinstead")
Hunter.create(name: "Jo Harvelle", age: 25, email: "notyouraveragejo@gmail.com", username: "RoadhouseJo", password: "strongerthanaman")
Hunter.create(name: "Bobby Singer", age: 62, email: "bsinger@gmail.com", username: "GunsNGasoline", password: "whiskeyaboveall")
Hunter.create(name: "Jody Mills", age: 52, email: "jodymills@gmail.com", username: "SiouFallsSheriff", password: "momoftheyear")

#MONSTERS
Monster.create(species: "vampire", lore: "Vampires are a race of blood-drinking supernatural creatures that were once human. Encountering a vampire is very rare as hunters have hunted them near to extinction although due to their ability to reproduce by transfusion there only needs to be one for them to repopulate. All vampires originate from the Alpha Vampire. Vampires must keep their victims alive or else their blood becomes toxic to them. However, some vampires will live off of donated blood bags because they don't want to kill a living being. A vampire's appearance is that of a normal human. However, they all have common features, such as sharp, pointed, retractable teeth that emerge from their gums and extend beyond their human teeth.", how_to_kill: "Vampires can only be killed by beheading, where they leave behind a corpse that can be examined to find their vampire teeth.")
Monster.create(species: "demon", lore: "Demons are the result of human souls going to Hell and being tortured until no humanity is left in them, thus turning into demons - dark, malicious spirits that revel in pain, chaos, and death. In this process, they become corrupted, extremely evil, and also very powerful. There are many ways of becoming a demon, from making a deal with a Crossroad Demon, to being a witch, and making a deal with another demon. They require a vessel(need to possess a human) to walk the Earth, though they are able to roam in the form of a long, slender cloud of black smoke. Possessed humans often look exactly the same as they did before possession, the only noticeable change being that their eyes will sometimes change color (black, red, white, grey, or yellow depending on the demon possessing them).", how_to_kill: "Demons cannot be killed but can be sent back to Hell by exorcism.")
Monster.create(species: "ghost", lore: "A Ghost is the spirit of a deceased person that, for some reason or another, was unable to pass on to the next life, or whose rest had been disturbed. Normally, a Ghost will start out confused and disoriented before realizing they are dead. In some cases, the trauma of sudden death can be so great that a Ghost will think that they are still alive and continue in a routine from their lives, oblivious to the fact they are dead. They typically reside in The Veil, but they can occasionally appear in the physical plane. Ghosts are often bound to an object or a place, normally the building they died/lived in or the area where they died, as such their movements are restricted, but this isn't universal, and some very powerful ghosts can move over larger distances, but unless they can move what they're bound to, they can never be totally free. They are also sometimes bound to their bodies unless their bodies have been put to rest. Descriptions of the apparition of ghosts vary widely: the mode of manifestation can range from an invisible presence to translucent or wispy shapes, to realistic, life-like visions.", how_to_kill: "Digging up a ghost's remains and salting and burning the bones, will help the spirit to cross over to the next life. When a ghost's bones are successfully salted and burned, it will go up in flames. This method is used for violent and vengeful spirits. Salting and burning the object the ghost is using to stay active in the human world, will put a ghost to rest if there are no bones to burn, or if the objects they considered to be extensions or remains of the spirit.")
Monster.create(species: "shapeshifter", lore: "Shapeshifters are human-like creatures that start out human, but later learn how to change their form to look like anyone they want. When exactly they learn is not consistent, some can learn from infancy, while others do not learn until much later in their lives. Due to starting off as humans, shapeshifters can have human urges and vices, such as greed, lust, etc. They are also arguably the most human monsters there are. Due to having human impulses and desires, shapeshifters are not driven by an instinct like vampires and werewolves and commit their acts by choice. When a shapeshifter takes the shape of the person they choose, they shed their skin, teeth and nails. When they change into the person's physical appearance, they access the thoughts of the person they are mimicking. Some shapeshifters are known to change their shape in a matter of seconds while others are known to take up to several hours. They can also take the forms of fictional characters or inhuman characteristics, such as vampire fangs or werewolf claws. In videos and cameras, a shifter's eyes will be a glowing silver-gold color.", how_to_kill: "They can be killed by a silver bullet or silver blade to the heart. Injuries caused by silver are incredibly painful to them while contact with a silver object will burn a shapeshifter and can be used as a method of identification of one.")
Monster.create(species: "werewolf", lore: "Werewolves are humanoid carnivores, the ultimate combination of wolves and humans. They feed on prey found nearby, which, due to the increase of urban areas, are mostly people. When they devour the flesh of a victim they leave a recognizable trace on the prey: they always eat the heart, although they do sometimes eat more of the body. The transformation only occurs after one bites a victim, the way werewolves continue the spread of lycanthropy. However, they are also capable of having children who are born werewolves. In their form, their bodies change rapidly, changing into a fitting definition of predators. Their nails increase to sharp, long claws, fangs increase in size and eyes resemble those of a wolf rather than of a human. Some of those who are bitten don't survive the change and the timing of the change can range from the next full moon to anytime at all with purebloods.", how_to_kill: "A werewolf's main weakness is their vulnerability to silver or any substance containing silver, as they can be killed with a silver knife or bullet. Contact with silver will hurt them.")

#CASES
Case.create(name: "Sawmill", location: "Texas", description: "A small town in Texas has had 5 missing persons cases in the past two weeks. 3 of those cases turned into murder investigations as they were found with large wounds on their necks and drained of blood.", hunter_id: 2, monster_id: 1)
Case.create(name: "Salvation", location: "Minesota", description: "A priest with connections to a hunter is brutally murdered. Signs in the area such as electrical storms and cattle mutilations point to a demon.", hunter_id: 3, monster_id: 2)
Case.create(name: "Bloody Mary", location: "Ohio", description: "A man is found dead in a pool of blood in his home. His daughter who found him claims she invoked a ghost named 'Bloody Mary' and caused his death.", hunter_id: 5, monster_id: 3)
Case.create(name: "Skin", location: "California", description: "Dean recieves a call from an old friend who is being charged for a murder he swears he did not commit. Footage shows the man at a bar like he says he was but also the scene of the crime with reflective eyes.", hunter_id: 1, monster_id: 4)
Case.create(name: "Heart", location: "Virginia", description: "A lawyer is found dead with his heart ripped out. Upon further investigation it is found that once a month 2-3 people are found dead with missing hearts.", hunter_id: 4, monster_id: 5)
Case.create(name: "Twihard", location: "Maryland", description: "4 girls have gone missing in a town in Maryland from a twilight themed club.", hunter_id: 1, monster_id: 1)
Case.create(name: "Blockade", location: "Oklahoma", description: "More storm activity than normal is documented in Oklahoma, especially in a town where all the citizens have blocked off their town.", hunter_id: 5, monster_id: 2)
Case.create(name: "House of Horror", location: "New York", description: "A local family reports being terrorized in the night by an invisible force.", hunter_id: 2, monster_id: 3)
Case.create(name: "Zombies?", location: "Florida", description: "Man who was pronouced dead a year ago is the lead suspect in a murder case that has local cops baffled.", hunter_id: 4, monster_id: 4)
Case.create(name: "Campsite Freight", location: "Kansas", description: "5 men who went camping were found at their campsite dead. They appear to have been mauled by a bear and are all missing their hearts", hunter_id: 3, monster_id: 5)
